spring:
  datasource:
    url: jdbc:h2:mem:waste
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
  port: 8081
